# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.5.1

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Support for parsing and rendering YAML documents"
HOMEPAGE="https://github.com/hasufell/streamly-yaml#readme"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"
IUSE="+no-examples +no-exe"

RDEPEND=">=dev-haskell/aeson-0.11:=[profile?]
	>=dev-haskell/attoparsec-0.11.3.0:=[profile?]
	>=dev-haskell/libyaml-streamly-0.2.3.0:=[profile?]
	dev-haskell/safe-exceptions:=[profile?]
	>=dev-haskell/scientific-0.3:=[profile?]
	>=dev-haskell/streamly-core-0.2.0:=[profile?] <dev-haskell/streamly-core-0.3:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/unordered-containers:=[profile?]
	dev-haskell/vector:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	!no-examples? ( dev-haskell/raw-strings-qq:=[profile?] )
	!no-exe? ( dev-haskell/optparse-applicative:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( dev-haskell/base-compat
		>=dev-haskell/hspec-1.3
		dev-haskell/hunit
		dev-haskell/mockery
		dev-haskell/temporary
		no-examples? ( dev-haskell/raw-strings-qq ) )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag no-examples no-examples) \
		$(cabal_flag no-exe no-exe)
}
