# Copyright 2024-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

CRATES="
	addr2line@0.24.2
	adler2@2.0.1
	autocfg@1.5.0
	backtrace-on-stack-overflow@0.3.0
	backtrace@0.3.75
	bitflags@1.3.2
	bitflags@2.9.1
	cc@1.2.32
	cfg-if@1.0.1
	crossterm@0.25.0
	crossterm_winapi@0.9.1
	displaydoc@0.2.5
	form_urlencoded@1.2.1
	gimli@0.31.1
	heck@0.5.0
	icu_collections@2.0.0
	icu_locale_core@2.0.0
	icu_normalizer@2.0.0
	icu_normalizer_data@2.0.0
	icu_properties@2.0.1
	icu_properties_data@2.0.1
	icu_provider@2.0.0
	idna@1.0.3
	idna_adapter@1.2.1
	indoc@2.0.6
	itoa@1.0.15
	libc@0.2.175
	litemap@0.8.0
	lock_api@0.4.13
	log@0.4.27
	lsp-types@0.93.2
	memchr@2.7.5
	memoffset@0.6.5
	memoffset@0.9.1
	miniz_oxide@0.8.9
	mio@0.8.11
	molc@0.3.0
	nix@0.23.2
	object@0.36.7
	once_cell@1.21.3
	parking_lot@0.12.4
	parking_lot_core@0.9.11
	percent-encoding@2.3.1
	portable-atomic@1.11.1
	potential_utf@0.1.2
	proc-macro2@1.0.97
	pyo3-build-config@0.25.1
	pyo3-ffi@0.25.1
	pyo3-macros-backend@0.25.1
	pyo3-macros@0.25.1
	pyo3@0.25.1
	quote@1.0.40
	redox_syscall@0.5.17
	rustc-demangle@0.1.26
	ryu@1.0.20
	scopeguard@1.2.0
	serde@1.0.219
	serde_derive@1.0.219
	serde_json@1.0.142
	serde_repr@0.1.20
	shlex@1.3.0
	signal-hook-mio@0.2.4
	signal-hook-registry@1.4.6
	signal-hook@0.3.18
	smallvec@1.15.1
	stable_deref_trait@1.2.0
	syn@1.0.109
	syn@2.0.104
	synstructure@0.13.2
	target-lexicon@0.13.2
	thread_local@1.1.9
	tinystr@0.8.1
	unicode-ident@1.0.18
	unicode-xid@0.2.6
	unindent@0.2.4
	url@2.5.4
	utf8_iter@1.0.4
	w-boson@0.1.0
	wasi@0.11.1+wasi-snapshot-preview1
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-core@0.58.0
	windows-implement@0.58.0
	windows-interface@0.58.0
	windows-result@0.2.0
	windows-strings@0.1.0
	windows-sys@0.48.0
	windows-targets@0.48.5
	windows-targets@0.52.6
	windows@0.58.0
	windows_aarch64_gnullvm@0.48.5
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_msvc@0.48.5
	windows_aarch64_msvc@0.52.6
	windows_i686_gnu@0.48.5
	windows_i686_gnu@0.52.6
	windows_i686_gnullvm@0.52.6
	windows_i686_msvc@0.48.5
	windows_i686_msvc@0.52.6
	windows_x86_64_gnu@0.48.5
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnullvm@0.48.5
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_msvc@0.48.5
	windows_x86_64_msvc@0.52.6
	writeable@0.6.1
	yoke-derive@0.8.0
	yoke@0.8.0
	zerofrom-derive@0.1.6
	zerofrom@0.1.6
	zerotrie@0.2.2
	zerovec-derive@0.11.1
	zerovec@0.11.4
"

inherit cargo

DESCRIPTION="The Erg programming language"
HOMEPAGE="https://erg-lang.org/"
SRC_URI="
	https://github.com/erg-lang/erg/archive/v${PV}/${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+="
	Apache-2.0-with-LLVM-exceptions MIT Unicode-3.0
	|| ( Apache-2.0 Boost-1.0 )
"
SLOT="0"
KEYWORDS="~amd64"
IUSE="+full-repl lsp +pretty unicode"

QA_FLAGS_IGNORED=".*"

src_configure() {
	local myfeatures=(
		$(usev lsp els)
		$(usev full-repl)
		$(usev unicode)
		$(usev pretty)
	)
	cargo_src_configure
}

src_test() {
	export ERG_PATH="${HOME}/.erg"
	cargo_src_test
}
