# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.3

EAPI=8

CRATES="
	addr2line@0.24.2
	adler2@2.0.0
	autocfg@1.4.0
	backtrace-on-stack-overflow@0.3.0
	backtrace@0.3.74
	bitflags@1.3.2
	bitflags@2.8.0
	cc@1.2.14
	cfg-if@1.0.0
	crossterm@0.25.0
	crossterm_winapi@0.9.1
	displaydoc@0.2.5
	form_urlencoded@1.2.1
	gimli@0.31.1
	heck@0.4.1
	icu_collections@1.5.0
	icu_locid@1.5.0
	icu_locid_transform@1.5.0
	icu_locid_transform_data@1.5.0
	icu_normalizer@1.5.0
	icu_normalizer_data@1.5.0
	icu_properties@1.5.1
	icu_properties_data@1.5.0
	icu_provider@1.5.0
	icu_provider_macros@1.5.0
	idna@1.0.3
	idna_adapter@1.2.0
	indoc@2.0.5
	itoa@1.0.14
	libc@0.2.169
	litemap@0.7.4
	lock_api@0.4.12
	log@0.4.25
	lsp-types@0.93.2
	memchr@2.7.4
	memoffset@0.6.5
	memoffset@0.9.1
	miniz_oxide@0.8.4
	mio@0.8.11
	molc@0.3.0
	nix@0.23.2
	object@0.36.7
	once_cell@1.20.3
	parking_lot@0.12.3
	parking_lot_core@0.9.10
	percent-encoding@2.3.1
	portable-atomic@1.10.0
	proc-macro2@1.0.93
	pyo3-build-config@0.21.2
	pyo3-ffi@0.21.2
	pyo3-macros-backend@0.21.2
	pyo3-macros@0.21.2
	pyo3@0.21.2
	quote@1.0.38
	redox_syscall@0.5.8
	rustc-demangle@0.1.24
	ryu@1.0.19
	scopeguard@1.2.0
	serde@1.0.217
	serde_derive@1.0.217
	serde_json@1.0.138
	serde_repr@0.1.19
	shlex@1.3.0
	signal-hook-mio@0.2.4
	signal-hook-registry@1.4.2
	signal-hook@0.3.17
	smallvec@1.14.0
	stable_deref_trait@1.2.0
	syn@1.0.109
	syn@2.0.98
	synstructure@0.13.1
	target-lexicon@0.12.16
	thread_local@1.1.8
	tinystr@0.7.6
	unicode-ident@1.0.16
	unicode-xid@0.2.6
	unindent@0.2.3
	url@2.5.4
	utf16_iter@1.0.5
	utf8_iter@1.0.4
	w-boson@0.1.0
	wasi@0.11.0+wasi-snapshot-preview1
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-core@0.58.0
	windows-implement@0.58.0
	windows-interface@0.58.0
	windows-result@0.2.0
	windows-strings@0.1.0
	windows-sys@0.48.0
	windows-targets@0.48.5
	windows-targets@0.52.6
	windows@0.58.0
	windows_aarch64_gnullvm@0.48.5
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_msvc@0.48.5
	windows_aarch64_msvc@0.52.6
	windows_i686_gnu@0.48.5
	windows_i686_gnu@0.52.6
	windows_i686_gnullvm@0.52.6
	windows_i686_msvc@0.48.5
	windows_i686_msvc@0.52.6
	windows_x86_64_gnu@0.48.5
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnullvm@0.48.5
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_msvc@0.48.5
	windows_x86_64_msvc@0.52.6
	write16@1.0.0
	writeable@0.5.5
	yoke-derive@0.7.5
	yoke@0.7.5
	zerofrom-derive@0.1.5
	zerofrom@0.1.5
	zerovec-derive@0.10.3
	zerovec@0.10.4
"

inherit cargo

DESCRIPTION="The Erg programming language"
HOMEPAGE="https://erg-lang.org/"
SRC_URI="
	https://github.com/erg-lang/erg/archive/v${PV}/${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+="
	Apache-2.0-with-LLVM-exceptions MIT Unicode-3.0
	|| ( Apache-2.0 Boost-1.0 )
"
SLOT="0"
KEYWORDS="~amd64"
IUSE="+full-repl lsp +pretty unicode"

QA_FLAGS_IGNORED=".*"

src_configure() {
	local myfeatures=(
		$(usev lsp els)
		$(usev full-repl)
		$(usev unicode)
		$(usev pretty)
	)
	cargo_src_configure
}

src_test() {
	export ERG_PATH="${HOME}/.erg"
	cargo_src_test
}
