# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.2

EAPI=8

CRATES="
	addr2line@0.21.0
	adler@1.0.2
	autocfg@1.1.0
	backtrace-on-stack-overflow@0.3.0
	backtrace@0.3.69
	bitflags@1.3.2
	cc@1.0.83
	cfg-if@1.0.0
	crossterm@0.25.0
	crossterm_winapi@0.9.1
	form_urlencoded@1.2.1
	gimli@0.28.1
	heck@0.4.1
	idna@0.5.0
	indoc@2.0.4
	itoa@1.0.10
	libc@0.2.153
	lock_api@0.4.11
	log@0.4.20
	lsp-types@0.93.2
	memchr@2.7.1
	memoffset@0.6.5
	memoffset@0.9.0
	miniz_oxide@0.7.2
	mio@0.8.10
	molc@0.2.8
	nix@0.23.2
	object@0.32.2
	once_cell@1.19.0
	parking_lot@0.12.1
	parking_lot_core@0.9.9
	percent-encoding@2.3.1
	proc-macro2@1.0.78
	pyo3-build-config@0.20.2
	pyo3-ffi@0.20.2
	pyo3-macros-backend@0.20.2
	pyo3-macros@0.20.2
	pyo3@0.20.2
	quote@1.0.35
	redox_syscall@0.4.1
	rustc-demangle@0.1.23
	ryu@1.0.16
	scopeguard@1.2.0
	serde@1.0.196
	serde_derive@1.0.196
	serde_json@1.0.113
	serde_repr@0.1.18
	signal-hook-mio@0.2.3
	signal-hook-registry@1.4.1
	signal-hook@0.3.17
	smallvec@1.13.1
	syn@1.0.109
	syn@2.0.48
	target-lexicon@0.12.13
	thread_local@1.1.7
	tinyvec@1.6.0
	tinyvec_macros@0.1.1
	unicode-bidi@0.3.15
	unicode-ident@1.0.12
	unicode-normalization@0.1.22
	unicode-xid@0.2.4
	unindent@0.2.3
	url@2.5.0
	wasi@0.11.0+wasi-snapshot-preview1
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-sys@0.48.0
	windows-targets@0.48.5
	windows_aarch64_gnullvm@0.48.5
	windows_aarch64_msvc@0.48.5
	windows_i686_gnu@0.48.5
	windows_i686_msvc@0.48.5
	windows_x86_64_gnu@0.48.5
	windows_x86_64_gnullvm@0.48.5
	windows_x86_64_msvc@0.48.5
"

inherit cargo

DESCRIPTION="The Erg programming language"
HOMEPAGE="https://erg-lang.org/"
SRC_URI="
	https://github.com/erg-lang/erg/archive/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+="
	Apache-2.0-with-LLVM-exceptions MIT Unicode-DFS-2016
	|| ( Apache-2.0 Boost-1.0 )
"
SLOT="0"
KEYWORDS="~amd64"
IUSE="+full-repl lsp +pretty unicode"

QA_FLAGS_IGNORED=".*"

src_configure() {
	local myfeatures=(
		$(usev lsp els)
		$(usev full-repl)
		$(usev unicode)
		$(usev pretty pretty)
	)
	cargo_src_configure
}
