# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.3

EAPI=8

CRATES="
	addr2line@0.22.0
	adler@1.0.2
	autocfg@1.3.0
	backtrace-on-stack-overflow@0.3.0
	backtrace@0.3.73
	bitflags@1.3.2
	bitflags@2.6.0
	cc@1.1.8
	cfg-if@1.0.0
	crossterm@0.25.0
	crossterm_winapi@0.9.1
	form_urlencoded@1.2.1
	gimli@0.29.0
	heck@0.4.1
	idna@0.5.0
	indoc@2.0.5
	itoa@1.0.11
	libc@0.2.155
	lock_api@0.4.12
	log@0.4.22
	lsp-types@0.93.2
	memchr@2.7.4
	memoffset@0.6.5
	memoffset@0.9.1
	miniz_oxide@0.7.4
	mio@0.8.11
	molc@0.3.0
	nix@0.23.2
	object@0.36.3
	once_cell@1.19.0
	parking_lot@0.12.3
	parking_lot_core@0.9.10
	percent-encoding@2.3.1
	portable-atomic@1.7.0
	proc-macro2@1.0.86
	pyo3-build-config@0.21.2
	pyo3-ffi@0.21.2
	pyo3-macros-backend@0.21.2
	pyo3-macros@0.21.2
	pyo3@0.21.2
	quote@1.0.36
	redox_syscall@0.5.3
	rustc-demangle@0.1.24
	ryu@1.0.18
	scopeguard@1.2.0
	serde@1.0.205
	serde_derive@1.0.205
	serde_json@1.0.122
	serde_repr@0.1.19
	signal-hook-mio@0.2.4
	signal-hook-registry@1.4.2
	signal-hook@0.3.17
	smallvec@1.13.2
	syn@1.0.109
	syn@2.0.72
	target-lexicon@0.12.16
	thread_local@1.1.8
	tinyvec@1.8.0
	tinyvec_macros@0.1.1
	unicode-bidi@0.3.15
	unicode-ident@1.0.12
	unicode-normalization@0.1.23
	unicode-xid@0.2.4
	unindent@0.2.3
	url@2.5.2
	wasi@0.11.0+wasi-snapshot-preview1
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-sys@0.48.0
	windows-targets@0.48.5
	windows-targets@0.52.6
	windows_aarch64_gnullvm@0.48.5
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_msvc@0.48.5
	windows_aarch64_msvc@0.52.6
	windows_i686_gnu@0.48.5
	windows_i686_gnu@0.52.6
	windows_i686_gnullvm@0.52.6
	windows_i686_msvc@0.48.5
	windows_i686_msvc@0.52.6
	windows_x86_64_gnu@0.48.5
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnullvm@0.48.5
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_msvc@0.48.5
	windows_x86_64_msvc@0.52.6
"

inherit cargo

DESCRIPTION="The Erg programming language"
HOMEPAGE="https://erg-lang.org/"
SRC_URI="
	https://github.com/erg-lang/erg/archive/v${PV}/${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+="
	Apache-2.0-with-LLVM-exceptions MIT Unicode-DFS-2016
	|| ( Apache-2.0 Boost-1.0 )
"
SLOT="0"
KEYWORDS="~amd64"
IUSE="+full-repl lsp +pretty unicode"

QA_FLAGS_IGNORED=".*"

src_configure() {
	local myfeatures=(
		$(usev lsp els)
		$(usev full-repl)
		$(usev unicode)
		$(usev pretty)
	)
	cargo_src_configure
}

src_test() {
	export ERG_PATH="${HOME}/.erg"
	cargo_src_test
}
